# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>
<function show at 0x7fd613058c20>


#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
x=[1,2,3]
print(np.size(x))

3


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info('shuffle')

     *** Found in numpy.random ***
shuffle(x)

Modify a sequence in-place by shuffling its contents.

This function only shuffles the array along the first axis of a
multi-dimensional array. The order of sub-arrays is changed but
their contents remains the same.

.. note::
    New code should use the ``shuffle`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
x : ndarray or MutableSequence
    The array, list or mutable sequence to be shuffled.

Returns
-------
None

See Also
--------
Generator.shuffle: which should be used for new code.

Examples
--------
>>> arr = np.arange(10)
>>> np.random.shuffle(arr)
>>> arr
[1 7 5 2 9 4 3 6 0 8] # random

Multi-dimensional arrays are only shuffled along the first axis:

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.shuffle(arr)
>>> arr
array([[3, 4, 5], # random
       [6, 7, 8],
       [0, 1, 2]])
-------------------------------------------------------------------------

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x=[1,2,3,4,5]
print(x[::-1])

[5, 4, 3, 2, 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
np.reshape(np.arange(0,9),(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
np.reshape(np.random.random(27),(3,3,3))

array([[[0.81058749, 0.76538449, 0.1167534 ],
        [0.37877207, 0.28892411, 0.4322007 ],
        [0.17507816, 0.69305514, 0.68861986]],

       [[0.94675002, 0.18815769, 0.3261888 ],
        [0.6637617 , 0.34055847, 0.10398007],
        [0.78207349, 0.84626503, 0.7974868 ]],

       [[0.18122728, 0.63627209, 0.84321847],
        [0.44557832, 0.50039693, 0.51029463],
        [0.80662713, 0.87727873, 0.11750643]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
x=np.reshape(np.random.random(100),(10,10))
print(np.min(x))
print(np.max(x))

0.0004740288137955462
0.9792549684760774


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
np.mean(np.random.random(30))

0.5194850165321648

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
x=np.reshape(np.ones(25),(5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
x=[[1,2,3],[4,5,6]]
np.pad(x,1)

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 0],
       [0, 4, 5, 6, 0],
       [0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
#results:
         #nan
         #false
         #false
         #nan
         #true
         #false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
x=np.zeros(64).reshape(8,8)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
np.unravel_index(100,(6,7,8),)

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
x=np.random.random(25).reshape(5,5)
print(x)
print('\n')
nor_x= (x - np.mean(x))/np.std(x)
print(nor_x)

[[0.94626497 0.11002635 0.09063077 0.80826037 0.85883774]
 [0.96185482 0.68641029 0.34397758 0.23724464 0.03387909]
 [0.50966668 0.41395842 0.75617096 0.48614359 0.05662834]
 [0.9884234  0.60556275 0.09648219 0.48873169 0.96366863]
 [0.66211046 0.85988975 0.67395103 0.85016461 0.79271653]]


[[ 1.19394044 -1.46851941 -1.53027206  0.75455424  0.91558508]
 [ 1.24357621  0.36660164 -0.72365338 -1.06347522 -1.710961  ]
 [-0.19612382 -0.50084474  0.58870926 -0.27101786 -1.63853078]
 [ 1.32816663  0.10919504 -1.51164202 -0.26277775  1.24935109]
 [ 0.28923459  0.91893453  0.32693321  0.88797113  0.70506494]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
x = np.arange(15).reshape(5,3)
y = np.arange(6).reshape(3,2)
np.matmul(x,y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
x= 10 * np.random.random(20)
print(x)
print('\n')
c=np.where((x>3) & (x<8) ,x*-1,x)
print(c)

[8.51668808 3.60155607 8.11472159 7.91613313 1.12323453 9.43578
 3.01030359 8.63133746 8.54592213 1.08008694 4.00703981 5.08873522
 1.57185815 3.74480374 2.12231014 4.78847968 6.41395623 5.7002634
 3.45841752 6.38987589]


[ 8.51668808 -3.60155607  8.11472159 -7.91613313  1.12323453  9.43578
 -3.01030359  8.63133746  8.54592213  1.08008694 -4.00703981 -5.08873522
  1.57185815 -3.74480374  2.12231014 -4.78847968 -6.41395623 -5.7002634
 -3.45841752 -6.38987589]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#the results:
#print(sum(range(5),-1)) =>9
#from numpy import *
print(sum(range(5),-1)) => 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z= np.arange(11)
# Z**Z => legal
# 2 << Z >> 2 => legal
# Z <- Z => legal
# 1j*Z   => legal
# Z/1/1  => legal
# Z<Z>Z  => ilegal

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# np.array(0) / np.array(0) => nan
# np.array(0) // np.array(0) => 0
# np.array([np.nan]).astype(int).astype(float) => array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
x=3*np.random.random(20)
print(x)
print(np.ceil(x))


[0.00888921 2.47679477 0.13698913 2.3410356  1.6810721  2.35080133
 2.34503478 0.63168063 2.96964896 1.46872409 0.15620901 2.95633216
 1.08661414 0.53915822 2.82218353 1.64116094 0.46732709 2.57334631
 2.63367888 1.09435835]
[1. 3. 1. 3. 2. 3. 3. 1. 3. 2. 1. 3. 2. 1. 3. 2. 1. 3. 3. 2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
x= np.arange(5,15)
y= np.arange(10,20)
np.intersect1d(x,y)

array([10, 11, 12, 13, 14])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.errstate(all='warn')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#the result:
#false

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
print('Today is : {}'.format(np.datetime64('TODAY','D')))
print('Tomorrow is : {}'.format(np.datetime64('Today','D')+ np.timedelta64(1, 'D')))
print('Yesteday is : {}'.format(np.datetime64('Today','D')- np.timedelta64(1, 'D')))

Today is : 2022-03-30
Tomorrow is : 2022-03-31
Yesteday is : 2022-03-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print('July, 2016')
print(np.arange('2016-07', '2016-08', dtype='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=50
B=10
x=np.add(A,B)
Y=np.negative(A)
z=np.multiply(x,Y)
np.divide(z,2)

-1500.0

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
x=10*np.random.random(10)
print(x)
print(np.floor(x))
print(np.trunc(x))
print(x.astype(int))
print(x-x%1)

[9.37790002 1.70104724 9.37316897 0.31634001 8.71270599 1.50574852
 8.74168616 5.81957143 2.36344009 4.56626179]
[9. 1. 9. 0. 8. 1. 8. 5. 2. 4.]
[9. 1. 9. 0. 8. 1. 8. 5. 2. 4.]
[9 1 9 0 8 1 8 5 2 4]
[9. 1. 9. 0. 8. 1. 8. 5. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
np.tile(np.arange(5),(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [3]:
iter=(2*x for x in range(10))
np.fromiter(iter,np.int16)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18], dtype=int16)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [4]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [8]:
x=np.random.random(10)
np.sort(x)

array([0.00684211, 0.02132178, 0.27288959, 0.51227537, 0.56376067,
       0.67036793, 0.68342181, 0.86852198, 0.91651038, 0.94805028])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [18]:
x=np.arange(5)
print(np.add.reduce(x))

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [19]:
a=np.random.random(5)
b=np.random.random(5)
np.array_equal(a,b)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [21]:
A=np.arange(10)
A.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [28]:
x=np.random.random(20).reshape(10,2)
y=np.random.random(20).reshape(10,2)
print('cartesian coordinates')
print(x)
print('\n')
print(y)
r=np.sqrt(x**2 + y**2)
phi=np.arctan2(x,y)
x=r * np.cos(phi)
y=r * np.sin(phi)
print('polar coordinates')
print(x)
print('\n')
print(y)

cartesian coordinates
[[0.40843738 0.74915416]
 [0.48026618 0.93578045]
 [0.77663738 0.40560548]
 [0.19051674 0.71968832]
 [0.7974749  0.70050294]
 [0.25145527 0.71667409]
 [0.80461188 0.84575476]
 [0.68273255 0.1948052 ]
 [0.81036858 0.53051446]
 [0.05226554 0.64973574]]


[[6.73542518e-01 6.34498340e-01]
 [4.48110179e-01 1.58844007e-01]
 [3.88334230e-01 6.44345221e-02]
 [4.66236573e-01 8.64459210e-01]
 [2.55955093e-01 9.80319286e-03]
 [3.49542860e-01 5.12307291e-02]
 [4.84043334e-01 2.05197607e-01]
 [2.65256360e-01 5.65172813e-01]
 [6.46903111e-01 8.38217453e-04]
 [5.13052654e-01 8.68875027e-01]]
polar coordinates
[[6.73542518e-01 6.34498340e-01]
 [4.48110179e-01 1.58844007e-01]
 [3.88334230e-01 6.44345221e-02]
 [4.66236573e-01 8.64459210e-01]
 [2.55955093e-01 9.80319286e-03]
 [3.49542860e-01 5.12307291e-02]
 [4.84043334e-01 2.05197607e-01]
 [2.65256360e-01 5.65172813e-01]
 [6.46903111e-01 8.38217453e-04]
 [5.13052654e-01 8.68875027e-01]]


[[0.40843738 0.74915416]
 [0.48026618 0.935

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [31]:
x=np.random.random(10)
x[np.argmax(x)]=0
print(x)

[0.79408199 0.84414041 0.51761727 0.3183769  0.74220409 0.66934143
 0.         0.33333804 0.58537722 0.552793  ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [66]:
Z = np.zeros((10,10), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,10),
                             np.linspace(0,1,10))
print(Z)

[[(0.        , 0.        ) (0.11111111, 0.        )
  (0.22222222, 0.        ) (0.33333333, 0.        )
  (0.44444444, 0.        ) (0.55555556, 0.        )
  (0.66666667, 0.        ) (0.77777778, 0.        )
  (0.88888889, 0.        ) (1.        , 0.        )]
 [(0.        , 0.11111111) (0.11111111, 0.11111111)
  (0.22222222, 0.11111111) (0.33333333, 0.11111111)
  (0.44444444, 0.11111111) (0.55555556, 0.11111111)
  (0.66666667, 0.11111111) (0.77777778, 0.11111111)
  (0.88888889, 0.11111111) (1.        , 0.11111111)]
 [(0.        , 0.22222222) (0.11111111, 0.22222222)
  (0.22222222, 0.22222222) (0.33333333, 0.22222222)
  (0.44444444, 0.22222222) (0.55555556, 0.22222222)
  (0.66666667, 0.22222222) (0.77777778, 0.22222222)
  (0.88888889, 0.22222222) (1.        , 0.22222222)]
 [(0.        , 0.33333333) (0.11111111, 0.33333333)
  (0.22222222, 0.33333333) (0.33333333, 0.33333333)
  (0.44444444, 0.33333333) (0.55555556, 0.33333333)
  (0.66666667, 0.33333333) (0.77777778, 0.33333333)
  (0.8888

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [35]:
x=10*np.random.random(5)
y=10*np.random.random(5)
c=1/(np.subtract.outer(x,y))
print(c)

[[-0.13316168 -0.14897193 -0.18332875  2.41443666 -0.27883719]
 [-0.45915498 -0.72415498 -8.13486467  0.17403624  0.57292403]
 [-0.3358726  -0.45864715 -1.08420696  0.20216216  1.05705268]
 [-1.94800664  3.52548738  0.64865948  0.13494369  0.29325507]
 [-0.14538978 -0.16444479 -0.20733655  0.95622313 -0.33844195]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [43]:
a=np.iinfo(np.int16)
print(a.min)
print(a.max)
b=np.iinfo(np.int32)
print(b.min)
print(b.max)

-32768
32767
-2147483648
2147483647


#### 49. How to print all the values of an array? (★★☆)

In [69]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((25,25))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [62]:
x=5
y=10* np.random.random(10)
print(y)
index = (np.abs(y-x)).argmin()
print(y[index])

[0.50626327 7.85893828 5.18093502 1.40099845 8.83691387 0.37901631
 2.10941519 0.45758519 0.66303157 1.01972194]
5.180935022776144


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [71]:
y = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(y)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [76]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.23170992 0.8509342  0.16883409 0.19674803 0.6579716
  0.19035643 0.37524688 0.82391708 0.37601089 0.65285989 0.83247196
  0.12166756 0.27660681 0.17252937 0.87578324 0.49065973 0.36467156
  0.42097871 0.30142178 0.12828168 0.93922731 0.21024649 0.69164165
  0.92034806 0.42535805 0.25657358 0.4008252  0.66313202 0.78371636
  0.45123798 0.12369058 0.89242448 0.79739903 0.82853894 0.90940922
  0.89738379 0.27093694 0.19048188 0.51405437 0.32661619 0.26127988
  0.32082634 0.74740933 0.49661147 0.54789986 0.89687114 0.42612514
  0.71040549 0.17981583 0.86666981 0.72545618 0.30075283 0.56706292
  0.63283675 0.53863693 0.58080913 0.6759704  0.55181894 0.74334667
  0.05920328 0.45871332 0.49411147 0.69602116 0.2792211  0.89532561
  0.3270226  0.67797905 0.4707635  0.46467861 0.3534373  0.87391591
  0.89000353 0.40542793 0.69770003 0.56410506 0.85111593 0.2741866
  0.58769332 0.7765766  0.54735533 0.33860832 0.42896671 0.67452559
  0.07910289 0.3262173  0.58728391 0.58312679 0.43

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [78]:
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [87]:
#please Create a txt file in your storage with upper data content Mr Baghbani jam
Z = np.genfromtxt("/content/txt", delimiter=",")
print(Z)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [88]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [89]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [90]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [93]:
X = np.random.rand(5, 6)
Y = X - X.mean(axis=1, keepdims=True)
print(X)
print(Y)

[[0.97693988 0.62793404 0.8013532  0.42163369 0.80161152 0.80612151]
 [0.38079013 0.22167494 0.66612209 0.73113118 0.45243831 0.96823328]
 [0.00366314 0.31789965 0.44493866 0.74543485 0.04220958 0.32438646]
 [0.20715751 0.04644619 0.31963746 0.05327362 0.80814125 0.93844981]
 [0.8219164  0.51630512 0.977582   0.03603393 0.31221803 0.22036766]]
[[ 0.23767424 -0.1113316   0.06208756 -0.31763195  0.06234588  0.06685587]
 [-0.18927486 -0.34839005  0.0960571   0.1610662  -0.11762668  0.39816829]
 [-0.30942559  0.00481092  0.13184994  0.43234613 -0.27087914  0.01129773]
 [-0.18836013 -0.34907145 -0.07588018 -0.34224402  0.41262361  0.54293217]
 [ 0.34117921  0.03556793  0.49684481 -0.44470326 -0.16851916 -0.26036953]]


#### 59. How to sort an array by the nth column? (★★☆)

In [94]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 7 0]
 [2 9 6]
 [3 5 4]]
[[3 5 4]
 [7 7 0]
 [2 9 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [95]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [97]:
Z = np.random.uniform(0,1,10)
z = 0.6
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


0.6155077241040405


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [99]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 5. 4. 2. 1. 5. 4. 2. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)